

CREATE DATABASE IF NOT EXISTS football;

USE football;

CREATE TABLE IF NOT EXISTS countries (
  country_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS teams (
  team_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  founded VARCHAR(255) NOT NULL,
  country_id INT,
  FOREIGN KEY (country_id) REFERENCES countries(country_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS players (
  player_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  country_id INT,
  team_id INT,
  appearances INT NOT NULL,
  goals INT NOT NULL,
  GOAT INT NOT NULL,
  FOREIGN KEY (country_id) REFERENCES countries(country_id),
  FOREIGN KEY (team_id) REFERENCES teams(team_id) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS winners (
  team_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  trophy VARCHAR(255) NOT NULL
);

INSERT INTO countries (name) VALUES
('England'),
('Scotland'),
('Wales'),
('Northern Ireland'),
('Republic of Ireland'),
('Spain'),
('Germany'),
('France'),
('Brazil'),
('Portugal'),
('USA'),
('Argintina'),
('Italy'),
('Holland'),
('Bulgaria'),
('Russia'),
('Ivory Coast'),
('Egypt'),
('Poland'),
('Belgium'),
('Ukraine');

INSERT INTO teams (name, founded, country_id) VALUES
('Arsenal FC', 1886, 1),
('Bournemouth AFC', 1899, 1),
('Everton', 1878, 1),
('Manchester City FC', 1880, 1),
('Liverpool FC', 1892, 1),
('Chelsea FC', 1905, 1),
('Newcastle United FC', 1892, 1),
('Leeds United', 1919, 1),
('Aston Villa FC', 1886, 1),
('Brighton & Hove Albion FC', 1901, 1),
('Nottingham Forest FC', 1865, 1),
('West Ham United FC', 1895, 1),
('Fulham FC', 1879, 1),
('Wolverhampton Wanderers FC', 1877, 1),
('Leicester City FC', 1884, 1),
('Brentford FC', 1889, 1),
('Southampton FC', 1885, 1),
('Crystal Palace FC', 1861, 1),
('Tottenham Hotspur FC', 1882, 1),
('Manchester United FC', 1878, 1),
('Barcelona', 1899, 6),
('Real Madrid', 1902, 6),
('Juventus', 1897, 13),
('Napoli', 1905, 13),
('Santos', 1912, 9),
('Dynamo Moscow', 1923, 16),
('Rangers FC (SCO)', 1872, 2),
('AC Milan', 1899, 13),
('Bayern Munich', 1900, 7),
('Benfica', 1904, 10),
('Paris SG', 1970, 8);

INSERT INTO players (name, position, age, country_id, team_id, appearances, goals, goat)
VALUES 
('Lionel Messi', 'FW', 34, 12, 21, 700, 600, 2),
('Cristiano Ronaldo', 'FW', 37, 10, 22, 800, 750, 2),
('Diego Maradona', 'FW', 60, 12, 24, 400, 250, 2),
('Pele', 'FW', 80, 9, 25, 500, 600, 2),
('Franz Beckenbauer', 'DF', 76, 5, 29, 400, 50, 2),
('Zinedine Zidane', 'MF', 49, 8, 22, 700, 100, 2),
('Johan Cruyff', 'FW', 68, 14, 21, 400, 200, 2),
('Michel Platini', 'MF', 66, 8, 23, 500, 150, 2),
('Lev Yashin', 'GK', 90, 16, 26, 450, 0, 2),
('George Best', 'FW', 59, 4, 20, 400, 150, 2),
('Eusebio', 'FW', 71, 10, 30, 500, 400, 1),
('Alfredo Di Stefano', 'FW', 90, 6, 22, 450, 400, 1),
('Bobby Charlton', 'MF', 84, 1, 20, 500, 200, 1),
('Roberto Baggio', 'FW', 54, 13, 23, 650, 300, 1),
('Paul Gascoigne', 'MF', 54, 1, 27, 450, 50, 1),
('Ronaldo', 'FW', 45, 9, 22, 550, 400, 1),
('Romario', 'FW', 56, 9, 21, 500, 300, 1),
('Marco van Basten', 'FW', 57, 14, 28, 400, 200, 1),
('Gary Lineker', 'FW', 61, 1, 15, 500, 300, 1),
('Hristo Stoichkov', 'FW', 55, 15, 21, 450, 200, 1),
('David Beckham', 'MF', 46, 1, 20, 750, 100, 1),
('Andres Iniesta', 'MF', 37, 6, 21, 600, 60, 1),
('Xavi', 'MF', 41, 6, 21, 700, 80, 1),
('Thierry Henry', 'FW', 44, 8, 1, 550, 350, 1),
('Dennis Bergkamp', 'FW', 52, 14, 1, 500, 200, 1),
('Patrick Vieira', 'MF', 45, 8, 1, 500, 50, 1),
('Cesc Fabregas', 'MF', 34, 6, 6, 650, 80, 1),
('Andriy Shevchenko', 'FW', 45, 21, 28, 500, 350, 1),
('Kylian Mbappé', 'FW', 23, 8, 31, 200, 120, 1),
('Neymar Jr.', 'FW', 29, 9, 31, 400, 200, 1),
('Kevin De Bruyne', 'MF', 30, 20, 4, 400, 80, 1),
('Robert Lewandowski', 'FW', 33, 19, 29, 500, 400, 1),
('Harry Kane', 'FW', 28, 1, 19, 450, 250, 1),
('Mohamed Salah', 'FW', 29, 18, 5, 400, 250, 1),
('Didier Drogba', 'FW', 43, 17, 6, 700, 380, 1),
('Steven Gerrard', 'MF', 41, 1, 5, 800, 190, 1),
('Frank Lampard', 'MF', 43, 1, 6, 900, 270, 1),
('Barry Ferguson', 'MF', 43, 2, 27, 600, 70, 1),
('Allan McGregor', 'GK', 40, NULL, 27, 744, 0, 2);




INSERT INTO winners (name, trophy) VALUES 
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Arsenal', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Manchester United', 'FA Cup'),
('Chelsea', 'FA Cup'),
('Chelsea', 'FA Cup'),
('Chelsea', 'FA Cup'),
('Chelsea', 'FA Cup'),
('Chelsea', 'FA Cup'),
('Chelsea', 'FA Cup'),
('Chelsea', 'FA Cup'),
('Chelsea', 'FA Cup'),
('Liverpool', 'FA Cup'),
('Liverpool', 'FA Cup'),
('Liverpool', 'FA Cup'),
('Liverpool', 'FA Cup'),
('Liverpool', 'FA Cup'),
('Liverpool', 'FA Cup'),
('Liverpool', 'FA Cup'),
('Liverpool', 'FA Cup'),
('Tottenham Hotspur', 'FA Cup'),
('Tottenham Hotspur', 'FA Cup'),
('Tottenham Hotspur', 'FA Cup'),
('Tottenham Hotspur', 'FA Cup'),
('Tottenham Hotspur', 'FA Cup'),
('Tottenham Hotspur', 'FA Cup'),
('Tottenham Hotspur', 'FA Cup'),
('Tottenham Hotspur', 'FA Cup'),
('Aston Villa', 'FA Cup'),
('Aston Villa', 'FA Cup'),
('Aston Villa', 'FA Cup'),
('Aston Villa', 'FA Cup'),
('Aston Villa', 'FA Cup'),
('Aston Villa', 'FA Cup'),
('Aston Villa', 'FA Cup'),
('Newcastle United', 'FA Cup'),
('Newcastle United', 'FA Cup'),
('Newcastle United', 'FA Cup'),
('Newcastle United', 'FA Cup'),
('Newcastle United', 'FA Cup'),
('Newcastle United', 'FA Cup'),
('Manchester City', 'FA Cup'),
('Manchester City', 'FA Cup'),
('Manchester City', 'FA Cup'),
('Manchester City', 'FA Cup'),
('Manchester City', 'FA Cup'),
('Manchester City', 'FA Cup'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester United', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Liverpool', 'Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Arsenal','Premier League'),
('Everton','Premier League'),
('Everton','Premier League'),
('Everton','Premier League'),
('Everton','Premier League'),
('Everton','Premier League'),
('Everton','Premier League'),
('Everton','Premier League'),
('Everton','Premier League'),
('Everton','Premier League'),
('Manchester City','Premier League'),
('Manchester City','Premier League'),
('Manchester City','Premier League'),
('Manchester City','Premier League'),
('Manchester City','Premier League'),
('Manchester City','Premier League'),
('Manchester City','Premier League'),
('Manchester City','Premier League'),
('Aston Villa','Premier League'),
('Aston Villa','Premier League'),
('Aston Villa','Premier League'),
('Aston Villa','Premier League'),
('Aston Villa','Premier League'),
('Aston Villa','Premier League'),
('Aston Villa','Premier League'),
('Chelsea','Premier League'),
('Chelsea','Premier League'),
('Chelsea','Premier League'),
('Chelsea','Premier League'),
('Chelsea','Premier League'),
('Chelsea','Premier League'),
('Sunderland','Premier League'),
('Sunderland','Premier League'),
('Sunderland','Premier League'),
('Sunderland','Premier League'),
('Sunderland','Premier League'),
('Sunderland','Premier League'),
('Liverpool','League Cup'),
('Liverpool','League Cup'),
('Liverpool','League Cup'),
('Liverpool','League Cup'),
('Liverpool','League Cup'),
('Liverpool','League Cup'),
('Liverpool','League Cup'),
('Liverpool','League Cup'),
('Liverpool','League Cup'),
('Manchester City','League Cup'),
('Manchester City','League Cup'),
('Manchester City','League Cup'),
('Manchester City','League Cup'),
('Manchester City','League Cup'),
('Manchester City','League Cup'),
('Manchester City','League Cup'),
('Manchester City','League Cup'),
('Manchester United','League Cup'),
('Manchester United','League Cup'),
('Manchester United','League Cup'),
('Manchester United','League Cup'),
('Manchester United','League Cup'),
('Manchester United','League Cup'),
('Aston Villa','League Cup'),
('Aston Villa','League Cup'),
('Aston Villa','League Cup'),
('Aston Villa','League Cup'),
('Aston Villa','League Cup'),
('Chelsea','League Cup'),
('Chelsea','League Cup'),
('Chelsea','League Cup'),
('Chelsea','League Cup'),
('Chelsea','League Cup'),
('Tottenham Hotspur','League Cup'),
('Tottenham Hotspur','League Cup'),
('Tottenham Hotspur','League Cup'),
('Tottenham Hotspur','League Cup'),
('Nottingham Forest','League Cup'),
('Nottingham Forest','League Cup'),
('Nottingham Forest','League Cup'),
('Nottingham Forest','League Cup'),
('Leicester City','League Cup'),
('Leicester City','League Cup'),
('Leicester City','League Cup');












